spring:
  profiles:
    active: dev

#mybatis plus 设置
mybatis-plus:
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.server.pojo
#  configuration:

# JWT
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: runyushop-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: Bearer  #JWT负载中拿到开头
