server:
  port: 8081

# Spring
spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/runyushop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # 配置druid
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      # 配置获取连接等待超时的时间
      maxWait: 60000

# mybatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.mingyang.admin.mapper: debug

